#!/usr/bin/env python3
"""Generate the 白い熊 音声 icon resources from shiroikuma/icon/onse-icon.svg.

Everything lands in the `onse` flavour source set, whose resources win over upstream's by name,
so upstream's own icon files are never edited:

  app/src/onse/res/drawable/ic_launcher_foreground.xml   adaptive foreground + monochrome (vector)
  app/src/onse/res/drawable/ic_launcher_background.xml   black ground (vector)
  app/src/onse/res/mipmap-*/ic_launcher.webp             legacy square icon per density
  app/src/onse/res/mipmap-*/ic_launcher_round.webp       legacy round icon per density
  shiroikuma/icon/onse-icon-512.png                      the README / preview image

Run shiroikuma/icon/trace-icon.py first if the SVG is missing.
Usage: python3 shiroikuma/icon/gen-icons.py
"""
import os
import re
import subprocess
import tempfile
import xml.etree.ElementTree as ET

from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SVG = os.path.join(ROOT, "shiroikuma/icon/onse-icon.svg")
RES = os.path.join(ROOT, "app/src/onse/res")
NS = "{http://www.w3.org/2000/svg}"
A = "http://schemas.android.com/apk/res/android"
DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}


def path_xml(el, indent):
    attrs = [f'android:pathData="{el.get("d")}"']
    if el.get("fill", "none") != "none":
        attrs.append(f'android:fillColor="{el.get("fill")}"')
    if el.get("stroke"):
        attrs += [f'android:strokeColor="{el.get("stroke")}"',
                  f'android:strokeWidth="{el.get("stroke-width")}"']
        if el.get("stroke-linecap"):
            attrs.append(f'android:strokeLineCap="{el.get("stroke-linecap")}"')
        if el.get("stroke-linejoin"):
            attrs.append(f'android:strokeLineJoin="{el.get("stroke-linejoin")}"')
    pad = " " * indent
    return f"{pad}<path\n" + "".join(f"{pad}    {a}\n" for a in attrs[:-1]) + f"{pad}    {attrs[-1]} />\n"


def foreground_vector():
    root = ET.parse(SVG).getroot()
    body = ""
    for el in root:
        tag = el.tag.replace(NS, "")
        if tag == "rect":                     # the black ground → ic_launcher_background
            continue
        if tag == "g":
            m = re.match(r"translate\(([-\d.]+),([-\d.]+)\) scale\(([-\d.]+)\)", el.get("transform"))
            tx, ty, s = m.groups()
            body += (f'    <group\n        android:translateX="{tx}"\n        android:translateY="{ty}"\n'
                     f'        android:scaleX="{s}"\n        android:scaleY="{s}">\n')
            for child in el:
                body += path_xml(child, 8)
            body += "    </group>\n"
        elif tag == "path":
            body += path_xml(el, 4)
    return (f'<?xml version="1.0" encoding="utf-8"?>\n'
            f'<!-- Generated by shiroikuma/icon/gen-icons.py from onse-icon.svg — do not edit. -->\n'
            f'<vector xmlns:android="{A}"\n    android:width="108dp"\n    android:height="108dp"\n'
            f'    android:viewportWidth="108"\n    android:viewportHeight="108">\n{body}</vector>\n')


BACKGROUND = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by shiroikuma/icon/gen-icons.py — the black ground of the 白い熊 音声 icon. -->
<vector xmlns:android="{A}"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#000000"
        android:pathData="M0,0h108v108h-108z" />
</vector>
'''


def render(size, out):
    subprocess.run(["rsvg-convert", "-w", str(size), "-h", str(size), SVG, "-o", out], check=True)


def main():
    os.makedirs(os.path.join(RES, "drawable"), exist_ok=True)
    with open(os.path.join(RES, "drawable/ic_launcher_foreground.xml"), "w", encoding="utf-8") as f:
        f.write(foreground_vector())
    with open(os.path.join(RES, "drawable/ic_launcher_background.xml"), "w", encoding="utf-8") as f:
        f.write(BACKGROUND)
    with tempfile.TemporaryDirectory() as tmp:
        for dens, px in DENSITIES.items():
            d = os.path.join(RES, f"mipmap-{dens}")
            os.makedirs(d, exist_ok=True)
            # Legacy icons show the safe-zone content: crop the 108 canvas to its middle 72 units.
            big = os.path.join(tmp, f"{dens}.png")
            render(px * 108 // 72, big)
            im = Image.open(big).convert("RGBA")
            off = (im.size[0] - px) // 2
            im = im.crop((off, off, off + px, off + px))
            sq = Image.new("L", im.size, 0)
            ImageDraw.Draw(sq).rounded_rectangle([0, 0, px - 1, px - 1], radius=int(px * 0.18), fill=255)
            square = im.copy(); square.putalpha(sq)
            square.save(os.path.join(d, "ic_launcher.webp"), "WEBP", lossless=True)
            rd = Image.new("L", im.size, 0)
            ImageDraw.Draw(rd).ellipse([0, 0, px - 1, px - 1], fill=255)
            round_ = im.copy(); round_.putalpha(rd)
            round_.save(os.path.join(d, "ic_launcher_round.webp"), "WEBP", lossless=True)
    render(512, os.path.join(ROOT, "shiroikuma/icon/onse-icon-512.png"))
    print("icons written to", RES)


if __name__ == "__main__":
    main()
